### ISSUE TITLE
Add dark mode toggle button

### ISSUE THREAD

**Issue by supzi-del** [DesignSystemsOSS/eccentrictouch#219]
Please can you assign this to me under LGM SOC'21?

**Comment by yashsehgal** [comment]
Hey, @supzi-del 👋🏽 Thanks for raising this issue.

This issue will be having a long phase of implementation/development as there will be JS methods involved in order to implement this feature properly. I would like you to also start a discussion based on this. So that, people can collaborate as well.

**Comment by supzi-del** [comment]
Yes, surely

**Comment by supzi-del** [comment]
Hey, where is the HTML file of the homepage located in the code?

**Comment by yashsehgal** [comment]
> page located in

If by homepage you mean, testing file for testing CSS then the path is (https://github.com/DesignSystemsOSS/eccentrictouch/tree/master/src/tests)

**Comment by supzi-del** [comment]
So where can I add this button?

**Comment by yashsehgal** [comment]
> So where can I add this button?

You can add the CSS for this in the `eccentric.scss` module.
`src\lib\eccentric.scss`

**Comment by 1anshu-56** [comment]
I want to work on this issue can you please assign it to me as I have work on issue like this earlier.

**Comment by supzi-del** [comment]
Hey is this the proper page I'm working on? Can I make a PR for this headings page?

https://user-images.githubusercontent.com/78655439/121660588-08cbb980-cac1-11eb-9c77-96fe4b608188.mp4
